name: Run container

on:
  workflow_call:
    inputs:
      PROJECT_ROOT_PATH:
        required: true
        type: string 
      ENVIRONMENT:
        required: true
        type: string
      PARAMETER:
        required: true
        type: string
      SERVICE_LOCATION_PATH:
        required: true
        type: string
      


jobs:
  run_container: 
    name: run the docker containers
    runs-on: 
      - ${{ inputs.ENVIRONMENT }}
    steps:
    - name: run up the container
      run: |-
        cd ${{ inputs.PROJECT_ROOT_PATH }}/current/${{inputs.SERVICE_LOCATION_PATH}}
        docker-compose ${{ inputs.PARAMETER }}