name: deploy to final destination
on:
  workflow_call:
    inputs:
      PROJECT_ROOT_PATH:
        required: true
        type: string 
      ENVIRONMENT:
        required: true
        type: string
      SERVICE_LOCATION_PATH:
        required: true
        type: string

env:
  KEEP_RELEASES: "4"

jobs:
  
  deploy_to_current:
    name: Deploy to folder
    runs-on: ${{inputs.ENVIRONMENT}}
    steps:
    - name: deploy to current folder
      run: |-
        cd ${{inputs.PROJECT_ROOT_PATH}}
        mkdir -p current
        rsync -rltgoEDvz --del --delete ${{inputs.PROJECT_ROOT_PATH}}/${GITHUB_SHA::7}/ ${{inputs.PROJECT_ROOT_PATH}}/current/
    - name: remove old folders
      run: |-
        cd ${{inputs.PROJECT_ROOT_PATH}}
        echo "$CI_PIPELINE_ID"
        ls -tr -I ${GITHUB_SHA::7} | head -n -$KEEP_RELEASES | xargs rm -rf

  
          